"""Add nacionalidad and estrato fields to Usuario model

Revision ID: 4d05efb960f9
Revises: 889fb9b675fe
Create Date: 2025-06-17 22:42:47.906164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d05efb960f9'
down_revision = '889fb9b675fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacionalidad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estrato', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('estrato')
        batch_op.drop_column('nacionalidad')

    # ### end Alembic commands ###
