"""Agregar campos de estudiante al modelo Usuario

Revision ID: 6dab78b17538
Revises: 
Create Date: 2025-06-17 16:41:03.109999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dab78b17538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tipo_documento', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('grado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seccion', sa.String(length=1), nullable=True))
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('admin', 'profesor', 'alumno', 'directivo', 'padre', name='rol_types'),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_usuarios_documento', ['documento'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('rol',
               existing_type=sa.Enum('admin', 'profesor', 'alumno', 'directivo', 'padre', name='rol_types'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('seccion')
        batch_op.drop_column('grado')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('genero')
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('tipo_documento')
        batch_op.drop_column('documento')

    # ### end Alembic commands ###
