"""agregar campos ciudad y barrio

Revision ID: 889fb9b675fe
Revises: 6dab78b17538
Create Date: 2025-06-17 19:12:32.133052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889fb9b675fe'
down_revision = '6dab78b17538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('barrio', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('barrio')
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###
